[profile.default]
version = "0.8.19"
src = "src"
out = "out"
libs = ["lib"]
eth_rpc_url = "CHAINSTACK_NODE_ENDPOINT"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
